var psalm95 = [ 
["Oh","come,","let","us","sing","to","the","Lord;"],
["let","us","make","a","joyful","noise","to","the","rock","of","our","salvation!"],
["Let","us","come","into","his","presence","with","thanksgiving;"],
["let","us","make","a","joyful","noise","to","him","with","songs","of","praise!"],
["For","the","Lord","is","a","great","God,"],
["and","a","great","King","above","all","gods."],
["In","his","hand","are","the","depths","of","the","earth;"],
["the","heights","of","the","mountains","are","his","also."],
["The","sea","is","his,","for","he","made","it,"],
["and","his","hands","formed","the","dry","land."],
["Oh","come,","let","us","worship","and","bow","down;"],
["let","us","kneel","before","the","Lord,","our","Maker!"],
["For","he","is","our","God,"],
["and","we","are","the","people","of","his","pasture,"],
["and","the","sheep","of","his","hand."], 
["Glory","be","to","the","Father", "and","to","the","Son"],
["And","to","the","Holy","Spirit"],
["As","it","was","in","the","beginning"],
["is","now","and","will","be","forever"],
["Amen"]
]
